name: Z2 - Build and Push Docker Image

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  ci_step:
    name: Build, scan and push Docker image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v4

      -
        name: Docker metadata definitions
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/nightxpl01/zadanko1-cld
          flavor: latest=true
          tags: |
            type=sha,priority=100,prefix=sha-,format=short
            type=semver,priority=200,pattern={{version}}

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Install Docker Scout CLI
        run: |
          curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh -s -- -b /usr/local/bin

      -
        name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build temporary image for vulnerability scan
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: false
          load: true
          tags: ghcr.io/nightxpl01/zadanko1-cld:temp
          cache-from: |
            type=registry,ref=docker.io/${{ vars.DOCKERHUB_USERNAME }}/zadanko1-cache:latest
          cache-to: |
            type=registry,ref=docker.io/${{ vars.DOCKERHUB_USERNAME }}/zadanko1-cache:latest,mode=max

      -
        name: Scan image for vulnerabilities
        run: |
          docker-scout cves ghcr.io/nightxpl01/zadanko1-cld:temp --format sarif --output cve-results.sarif
          SEVERITY_COUNT=$(docker-scout cves ghcr.io/nightxpl01/zadanko1-cld:temp --format json | grep -E '"severity":"(high|critical)"' | wc -l)
          echo "Found $SEVERITY_COUNT high/critical vulnerabilities"
          test "$SEVERITY_COUNT" -eq 0

      -
        name: Build and push Docker image (only if scan passed)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: |
            type=registry,ref=docker.io/${{ vars.DOCKERHUB_USERNAME }}/zadanko1-cache:latest
          cache-to: |
            type=registry,ref=docker.io/${{ vars.DOCKERHUB_USERNAME }}/zadanko1-cache:latest,mode=max
